dep ensure + fix etcd build errors

diff --git a/vendor/github.com/coreos/go-systemd/test b/vendor/github.com/coreos/go-systemd/test
--- a/vendor/github.com/coreos/go-systemd/test
+++ b/vendor/github.com/coreos/go-systemd/test
@@ -24,15 +24,17 @@ if [ -z "$GOPATH" ]; then
 	fi
 	export GOPATH=${PWD}/gopath
 	go get -u github.com/godbus/dbus
+	go get -u github.com/coreos/pkg/dlopen
 fi
 
-TESTABLE="activation journal login1 machine1 unit"
-FORMATTABLE="$TESTABLE sdjournal dbus"
+TESTABLE="activation daemon journal login1 unit"
+FORMATTABLE="$TESTABLE sdjournal dbus machine1"
 if [ -e "/run/systemd/system/" ]; then
+	# if we're on a systemd-system, we can test sdjournal
 	TESTABLE="${TESTABLE} sdjournal"
 	if [ "$EUID" == "0" ]; then
-		# testing actual systemd behaviour requires root
-		TESTABLE="${TESTABLE} dbus"
+		# testing actual systemd/machined behaviour requires root
+		TESTABLE="${TESTABLE} dbus machine1"
 	fi
 fi
 
@@ -57,7 +59,7 @@ split=(${TEST// / })
 TEST=${split[@]/#/${REPO_PATH}/}
 
 echo "Running tests..."
-go test ${COVER} $@ ${TEST}
+go test -v ${COVER} $@ ${TEST}
 
 echo "Checking gofmt..."
 fmtRes=$(gofmt -l $FMT)
@@ -72,5 +74,15 @@ if [ -n "${vetRes}" ]; then
 	echo -e "govet checking failed:\n${vetRes}"
 	exit 255
 fi
+
+echo "Checking for license header..."
+licRes=$(for file in $(find . -type f -iname '*.go' ! -path './gopath/*'); do
+		head -n3 "${file}" | grep -Eq "(Copyright|generated|GENERATED)" || echo -e "  ${file}"
+	done;)
+if [ -n "${licRes}" ]; then
+	echo -e "license header checking failed:\n${licRes}"
+	exit 255
+fi
+
 
 echo "Success"
